name : MockDataStoreService release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    name: Create MockDataStoreService release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.0
      with:
        submodules: recursive

    - name: Setup foreman
      uses: rojo-rbx/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build default.project.json
      run: |
        rojo build default.project.json --output MockDataStoreService.rbxmx

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
    
    - name: Upload MockDataStoreService.rbxmx
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: MockDataStoreService.rbxmx
        asset_content_type: application/xml
